import Foundation

extension Strings {

    static let events: [String: Pair] = [
        "event.hatched": ("%@ saiu do ovo.", "%@ hatched from its egg."),
        "event.evolved": ("%@ cresceu e chegou à fase %@.", "%@ grew up and reached the %@ stage."),
        "event.becameForm": ("%@ tornou-se %@.", "%@ became %@."),
        "event.gotSick": ("%@ ficou doente.", "%@ got sick."),
        "event.recovered": ("%@ recuperou com o remédio.", "%@ recovered with medicine."),
        "event.ateTooMuch": ("%@ comeu snacks a mais.", "%@ ate too many snacks."),
        "event.farewell": ("%@ regressou ao seu planeta.", "%@ returned to its home planet."),
        "event.pooped": ("Fez cocó %d vezes", "Pooped %d times"),
        "event.slept": ("Dormiu uma sesta", "Took a nap"),
        "event.tantrums": ("Fez %d birras", "Threw %d tantrums"),
    ]

    static let overlays: [String: Pair] = [
        "away.title": ("Enquanto estiveste fora", "While you were away"),
        "away.duration": ("Estiveste fora %@", "You were away for %@"),
        "away.nothing": ("Portou-se bem, nada de especial.", "It behaved, nothing special happened."),
        "away.needs": ("Como estão as necessidades", "How its needs changed"),
        "evolution.rare": ("RARO", "RARE"),
        "evolution.title": ("Está a crescer!", "It's growing up!"),
        "evolution.became": ("%@ é agora %@", "%@ is now %@"),
        "farewell.title": ("Até sempre, %@", "Farewell, %@"),
        "farewell.oldAge": ("Depois de uma vida longa e feliz, %@ regressou ao seu planeta entre as estrelas. Vai lembrar-se sempre de ti.",
                            "After a long, happy life, %@ returned to its planet among the stars. It will always remember you."),
        "farewell.neglect": ("%@ sentiu-se sozinho e voltou para o seu planeta, onde vão cuidar bem dele. Da próxima vez, visita-o mais vezes.",
                             "%@ felt lonely and went back to its planet, where it will be well looked after. Next time, visit more often."),
        "farewell.lived": ("Viveu %@", "Lived %@"),
        "farewell.newEgg": ("Receber um novo ovo", "Receive a new egg"),
    ]

    static let games: [String: Pair] = [
        "games.title": ("Mini-jogos", "Mini-games"),
        "games.subtitle": ("Brincar dá felicidade e moedas, mas cansa.", "Playing brings happiness and coins, but it's tiring."),
        "games.energyCost": ("-12 energia", "-12 energy"),
        "game.leftRight": ("Esquerda ou Direita", "Left or Right"),
        "game.leftRight.desc": ("Adivinha para que lado vai olhar.", "Guess which way it will look."),
        "game.catchStars": ("Apanha as Estrelas", "Catch the Stars"),
        "game.catchStars.desc": ("Arrasta ou inclina para apanhar estrelas.", "Drag or tilt to catch falling stars."),
        "game.rhythm": ("Ritmo", "Rhythm Tap"),
        "game.rhythm.desc": ("Toca quando o círculo encontra o anel.", "Tap when the circle meets the ring."),
        "game.win": ("Ganhaste!", "You won!"),
        "game.lose": ("Quase!", "So close!"),
        "game.score": ("Pontos: %d", "Score: %d"),
        "game.coins": ("+%d moedas", "+%d coins"),
        "game.ready": ("Prepara-te…", "Get ready…"),
        "lr.prompt": ("Para onde vai olhar?", "Which way will it look?"),
        "lr.left": ("Esquerda", "Left"),
        "lr.right": ("Direita", "Right"),
        "lr.round": ("Ronda %d de %d", "Round %d of %d"),
        "lr.correct": ("Acertaste!", "Correct!"),
        "lr.wrong": ("Falhaste!", "Missed!"),
        "stars.time": ("%d s", "%d s"),
        "stars.hint": ("Evita as nuvens de chuva!", "Avoid the rain clouds!"),
        "rhythm.tap": ("TOCA", "TAP"),
        "rhythm.perfect": ("Perfeito!", "Perfect!"),
        "rhythm.good": ("Bom!", "Good!"),
        "rhythm.miss": ("Falhou", "Miss"),
    ]

    static let shop: [String: Pair] = [
        "shop.title": ("Loja", "Shop"),
        "shop.hats": ("Chapéus", "Hats"),
        "shop.decor": ("Decoração", "Decor"),
        "shop.wallpapers": ("Paredes", "Walls"),
        "shop.owned": ("Teu", "Owned"),
        "shop.wear": ("Usar", "Wear"),
        "shop.wearing": ("A usar", "Wearing"),
        "shop.remove": ("Tirar", "Take off"),
        "shop.apply": ("Aplicar", "Apply"),
        "shop.applied": ("Aplicado", "Applied"),
        "shop.free": ("Grátis", "Free"),
        "item.hat.bow": ("Laço", "Bow"),
        "item.hat.cap": ("Boné", "Cap"),
        "item.hat.flower": ("Flor", "Flower"),
        "item.hat.party": ("Chapéu de festa", "Party hat"),
        "item.hat.headphones": ("Auscultadores", "Headphones"),
        "item.hat.crown": ("Coroa", "Crown"),
        "item.decor.plant": ("Planta", "Plant"),
        "item.decor.lamp": ("Candeeiro", "Floor lamp"),
        "item.decor.sofa": ("Sofá", "Sofa"),
        "item.decor.painting": ("Quadro", "Painting"),
        "item.decor.books": ("Estante", "Bookshelf"),
        "item.decor.bed": ("Cama", "Bed"),
        "item.decor.teddy": ("Peluche", "Teddy bear"),
        "item.decor.tree": ("Árvore", "Tree"),
        "item.decor.fish": ("Lago dos peixes", "Fish pond"),
        "item.decor.tent": ("Tenda", "Tent"),
        "item.wall.warm": ("Clássico", "Classic"),
        "item.wall.stripes": ("Riscas", "Stripes"),
        "item.wall.dots": ("Bolinhas", "Polka dots"),
        "item.wall.stars": ("Estrelas", "Stars"),
        "item.wall.forest": ("Floresta", "Forest"),
    ]

    static let album: [String: Pair] = [
        "album.title": ("Memórias", "Memories"),
        "album.family": ("Álbum da Família", "Family Album"),
        "album.journal": ("Diário", "Journal"),
        "album.emptyFamily": ("Ainda não há memórias. Cada animal que regressar ao seu planeta fica aqui guardado.",
                              "No memories yet. Every pet that returns to its planet is kept here."),
        "album.emptyJournal": ("O diário enche-se com os momentos marcantes da vida do teu animal.",
                               "The journal fills up with the big moments of your pet's life."),
        "album.reached": ("Chegou a %@", "Reached %@"),
        "album.reason.oldAge": ("Velhice feliz", "Happy old age"),
        "album.reason.neglect": ("Sentiu-se sozinho", "Felt lonely"),
    ]

    static let stats: [String: Pair] = [
        "stats.title": ("Progresso", "Progress"),
        "stats.tabStats": ("Estatísticas", "Stats"),
        "stats.tabAchievements": ("Conquistas", "Achievements"),
        "stats.petsRaised": ("Animais criados", "Pets raised"),
        "stats.meals": ("Refeições", "Meals"),
        "stats.snacks": ("Snacks", "Snacks"),
        "stats.baths": ("Banhos", "Baths"),
        "stats.cleanings": ("Limpezas", "Cleanings"),
        "stats.medicines": ("Remédios", "Medicines"),
        "stats.caresses": ("Festinhas", "Cuddles"),
        "stats.gamesPlayed": ("Jogos", "Games played"),
        "stats.gamesWon": ("Vitórias", "Games won"),
        "stats.coinsEarned": ("Moedas ganhas", "Coins earned"),
        "stats.longestLife": ("Vida mais longa", "Longest life"),
        "stats.unlocked": ("%d de %d desbloqueadas", "%d of %d unlocked"),
    ]

    static let achievements: [String: Pair] = [
        "ach.firstHatch": ("Primeiro ovo", "First egg"),
        "ach.firstHatch.desc": ("Choca o teu primeiro ovo.", "Hatch your first egg."),
        "ach.firstSteps": ("Primeiros passos", "First steps"),
        "ach.firstSteps.desc": ("Chega à fase de criança.", "Reach the child stage."),
        "ach.grownUp": ("Crescido", "All grown up"),
        "ach.grownUp.desc": ("Chega à fase adulta.", "Reach adulthood."),
        "ach.goldenYears": ("Anos dourados", "Golden years"),
        "ach.goldenYears.desc": ("Chega à fase sénior.", "Reach the senior stage."),
        "ach.rareForm": ("Raridade", "Rare find"),
        "ach.rareForm.desc": ("Descobre uma forma adulta rara.", "Discover a rare adult form."),
        "ach.tidy": ("Arrumadinho", "Neat freak"),
        "ach.tidy.desc": ("Limpa 20 vezes.", "Clean up 20 times."),
        "ach.gamer": ("Jogador", "Gamer"),
        "ach.gamer.desc": ("Ganha 10 mini-jogos.", "Win 10 mini-games."),
        "ach.saver": ("Poupado", "Saver"),
        "ach.saver.desc": ("Junta 300 moedas.", "Save up 300 coins."),
        "ach.shopper": ("Colecionador", "Collector"),
        "ach.shopper.desc": ("Tem 6 artigos da loja.", "Own 6 shop items."),
        "ach.weekOld": ("Uma semana", "One week"),
        "ach.weekOld.desc": ("Mantém o animal vivo 7 dias.", "Keep your pet alive for 7 days."),
        "ach.perfectCare": ("Cuidado perfeito", "Perfect care"),
        "ach.perfectCare.desc": ("Todas as necessidades acima de 90.", "Every need above 90."),
        "ach.fashion": ("Na moda", "Fashionista"),
        "ach.fashion.desc": ("Põe um chapéu ao teu animal.", "Put a hat on your pet."),
    ]

    static let settings: [String: Pair] = [
        "settings.title": ("Definições", "Settings"),
        "settings.language": ("Idioma", "Language"),
        "settings.appearance": ("Aparência", "Appearance"),
        "settings.theme.system": ("Sistema", "System"),
        "settings.theme.light": ("Claro", "Light"),
        "settings.theme.dark": ("Escuro", "Dark"),
        "settings.audio": ("Som e toque", "Sound & touch"),
        "settings.sound": ("Efeitos sonoros", "Sound effects"),
        "settings.music": ("Música", "Music"),
        "settings.haptics": ("Vibração", "Haptics"),
        "settings.notifications": ("Notificações", "Notifications"),
        "settings.notificationsHint": ("Avisa quando o teu animal precisa de ti.", "Get a nudge when your pet needs you."),
        "settings.notificationsDenied": ("As notificações estão desligadas nas Definições do sistema.",
                                         "Notifications are turned off in the system Settings."),
        "settings.gameplay": ("Jogo", "Gameplay"),
        "settings.demo": ("Modo demo (60× mais rápido)", "Demo mode (60× faster)"),
        "settings.demoHint": ("Uma hora passa num minuto. Para testar a evolução.",
                              "An hour passes in a minute. Handy for testing evolution."),
        "settings.reset": ("Recomeçar do zero", "Start over"),
        "settings.resetTitle": ("Recomeçar do zero?", "Start over?"),
        "settings.resetMessage": ("Apaga o animal atual, as moedas, a loja e as estatísticas. O álbum e o diário também.",
                                  "Deletes the current pet, coins, shop items and stats. The album and journal too."),
        "settings.info": ("Informação", "Information"),
        "settings.howToPlay": ("Como jogar", "How to play"),
        "settings.about": ("Sobre", "About"),
    ]
}
